[repository]
name = "PortalBrasil: Core"
managed_by_uv = true
changelog = "CHANGELOG.md"
version = "version.txt"
compose = ""

[repository.towncrier]
section = "Projeto"
settings = "towncrier.toml"

[backend]
path = "backend"

[backend.package]
name = "portalbrasil.core"
path = "backend"
changelog = "backend/CHANGELOG.md"
towncrier_settings = "backend/pyproject.toml"
base_package = "Products.CMFPlone"
publish = true

[frontend]
path = "frontend"

[frontend.package]
name = "@portalbrasil/core"
path = "frontend/packages/core"
changelog = "frontend/packages/core/CHANGELOG.md"
towncrier_settings = "frontend/packages/core/towncrier.toml"
publish = true
